config/routes.rb
Rails.application.routes.draw do
  
  get 'users/new'
  root 'static_page#home'
  get 'help' => 'static_page#help'
  get 'about' => 'static_page#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :microposts,          only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts, dependent: :destroy
    attr_accessor :remember_token
    before_save { self.username = username.downcase }
    validates :username, presence: true, length: {maximum: 50}, uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: {minimum: 6}, allow_blank: true

    has_secure_password
    has_secure_password :recovery_password, validations: false

    def User.digest(string)    
        cost = ActiveModel::SecurePassword.min_cost ?            
        BCrypt::Engine::MIN_COST :           
        BCrypt::Engine.cost    
        BCrypt::Password.create(string, cost: cost)  
    end

    def feed    
        Micropost.where("user_id = ?", id)  
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token    
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)    
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)  
    end

    def forget    
        update_attribute(:remember_digest, nil)  
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    protect_from_forgery with: :exception  
    include SessionsHelper

    def logged_in_user      
        unless logged_in?    
          store_location    
          flash[:danger] = "Please log in."        
          redirect_to login_url      
        end    
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]  
    def create  
        @micropost = current_user.microposts.build(micropost_params)    
        if @micropost.save      
            flash[:success] = "Micropost created!"      
            redirect_to root_url    
        else      
            render 'static_pages/home'    
        end
    end  
    def destroy  
        Micropost.find(params[:id]).destroy    
        flash[:success] = "Micropost deleted"    
        redirect_to root_url 
    end


    private    
        def micropost_params      
            params.require(:micropost).permit(:content)    
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  def current_user?(user)    
    user == current_user  
  end
  
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController

  def help
  end

  def home
    if logged_in?      
      @micropost = current_user.microposts.build     
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    # debugger
  end

  def destroy    
    User.find(params[:id]).destroy    
    flash[:success] = "User deleted"    
    redirect_to users_url  
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
      # debugger
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update    
    @user = User.find(params[:id])    
    if @user.update(user_params)
      flash[:success] = "Profile updated"      
      redirect_to @user
    else      
      render 'edit'    
    end  
  end

  def correct_user      
    @user = User.find(params[:id])      
    redirect_to(root_url) unless current_user?(@user)    
  end

  private   

    def user_params      
      params.require(:user).permit(:username, :password, :password_confirmation)    
    end

    def admin_user
      direct_to(root_url) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def remember(user)    
        user.remember    
        cookies.permanent.signed[:user_id] = user.id    
        cookies.permanent[:remember_token] = user.remember_token  
    end

    def current_user    
        if (user_id = session[:user_id])      
            @current_user ||= User.find_by(id: user_id)    
        elsif (user_id = cookies.signed[:user_id])      
            user = User.find_by(id: user_id)      
            if user && user.authenticated?(cookies[:remember_token])        
                log_in user        
                @current_user = user      
            end    
        end  
    end

    def current_user?(user)    
        user == current_user  
    end

    def logged_in?
        !current_user.nil?
    end

    def redirect_back_or(default)    
        redirect_to(session[:forwarding_url] || default)    
        session.delete(:forwarding_url)
    end

    def store_location    
        session[:forwarding_url] = request.url if request.get?  
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def forget(user)    
        user.forget    
        cookies.delete(:user_id)    
        cookies.delete(:remember_token)  
    end

    
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 50 })
        gravatar_id = Digest::MD5::hexdigest(user.username.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "gravatar")
    end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to 'sample app', root_path, id: "logo" %>
    <nav>
        <ul class="nav navbar-nav navbar-right">            
            <li><%= link_to "Home", root_path  %></li>
            <li><%= link_to "Help", help_path %></li>

            <% if logged_in? %>       
                <%= link_to "Users", users_path %></li>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>            
                <ul class="dropdown-menu">              
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user)  %></li>              
                    <li class="divider"></li>              
                    <li><%= button_to "Logout", logout_path, method: "delete" %></li>            
                </ul>           
                </li>        
            <% else %>          
                <li><%= link_to "Log in", login_path %></li>    
                <li> <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %> </li>
            <% end %>

        </ul>
    </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>


    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>

    
    
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">  
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>  
    
    <span class="user">
        <%= link_to micropost.user.username, micropost.user %>
    </span>  
    
    <span class="content">
        <%= micropost.content %>
    </span>

    <span class="timestamp">Posted
        <%= time_ago_in_words(micropost.created_at) %>ago.
    </span>

    <%= link_to "delete", micropost, data: {turbo_method: :delete} %> 

</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>  
    <div id="error_explanation">    
        <div class="alert alert-danger">      
        The form contains <%= pluralize(object.errors.count, "error") %>.    
        </div>    
        <ul>    
            <% object.errors.full_messages.each do |msg| %>      
            <li><%= msg %></li>    
            <% end %>    
        </ul>  
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>  
    <ol class="microposts">    
        <%= render @feed_items %>  
    </ol>  
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>  
    <%= render 'shared/error_messages', object: f.object %>  
    <div class="field">    
        <%= f.text_area :content, placeholder: "Compose new micropost..." %>  
    </div>  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.username %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_page/about.html.erb
<% provide(:title, "About") %>
<h1>App</h1>    
<p>This is About Page</p>  

app/views/static_page/help.html.erb
<% provide(:title, "Help") %>

<h1>App</h1>    
<p>This is Help Page</p>  

app/views/static_page/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>  
    <div class="row">    
        <aside class="col-md-4">      
            <section class="user_info">        
                <%= render 'shared/user_info' %>      
            </section>      
            <section class="micropost_form">        
                <%= render 'shared/micropost_form' %>      
            </section>    
        </aside>  
        <div class="col-md-8">      
            <h3>Micropost Feed</h3>      
            <%= render 'shared/feed' %>    
        </div>
    </div>
<% else %>

<h1>App</h1>    
<p>This is Home Page</p>  

<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">  
    <div class="col-md-6 col-md-offset-3">    
        <%= form_for(@user) do |f| %>      
        <%= render 'shared/error_messages', object: f.object %>      
        <%= f.label :username %>      
        <%= f.text_field :username, class: 'form-control' %>       
        <%= f.label :password %>      
        <%= f.password_field :password, class: 'form-control' %>      
        <%= f.label :password_confirmation, "Confirmation" %>      
        <%= f.password_field :password_confirmation, class: 'form-control' %>      
        <%= f.submit "Save changes", class: "btn btn-primary" %>    
        <% end %>    
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<ul class="users">  
    <% @users.each do |user| %>    
        <li>         
        <%= link_to user.username, user %>   
        <% if current_user.admin? && !current_user?(user) %>    
        | <%= link_to "delete", user, data: { confirm: "You sure?", "turbo-method": :delete } %>  
        <% end %> 
        </li>  
    <% end %>
</ul>g

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">  
    <div class="col-md-6 col-md-offset-3">    
        <%= form_for(@user) do |f| %>      
        <%= render 'shared/error_messages', object: f.object %>      
        <%= f.label :username %>      
        <%= f.text_field :username, class: 'form-control' %>       
        <%= f.label :password %>      
        <%= f.password_field :password, class: 'form-control' %>      
        <%= f.label :password_confirmation, "Confirmation" %>      
        <%= f.password_field :password_confirmation, class: 'form-control' %>      
        <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>  
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">  
    <aside class="col-md-4">    
        <section class="user_info">      
            <h1>  
                <%= gravatar_for @user %>  
                <%= @user.username %>
            </h1>  
        </section>  
    </aside>

    <div class="col-md-8">    
        <% if @user.microposts.any? %>      
        <h3>Microposts (<%= @user.microposts.count %>)</h3>      
        <ol class="microposts">        
            <%= render @microposts %>      
        </ol>      
        <%= will_paginate @microposts %>    
        <% end %>  
    </div>
</div>